<?php

namespace App\Controller;

use Cake\Controller\Controller;

class EventsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // Allow methods
        // $this->Auth->allow(['logout', 'add']);
    }

    public function index()
    {
        $events = $this->Events->find()->contain(['Users']);
        $this->set(compact('events'));
    }

    public function view($id)
    {
        $event = $this->Events->get($id, ['contain' => ['Users',]]);
        $this->set(compact('event'));
    }

    public function add()
    {
        $n = $this->Events->newEntity();
        $this->set(compact('n'));

        // Get the current user information
        $u = $this->Auth->user();
        // Define user_id from current auth id
        $n->user_id = $u['id'];

        // Check if is from post method
        if ($this->request->is(['post'])) {
            // Get form data
            $n = $this->Events->patchEntity($n, $this->request->getData());
            // Test saving record on database
            if ($result = $this->Events->save($n)) {
                $this->Flash->success('Votre événement a été correctement ajouté');
                return $this->redirect(['action' => 'index']);
            }
            // Error while trying to save
            $this->Flash->error('Une erreur est survenue. Veuillez réessayer.');
        }
    }
}
